### ISSUE TITLE
OS Support

### ISSUE THREAD

**Issue by arunganesh-a** [hilleer/kill-port-process#27]
Hi,

Will this library work for Windows as well as mac and Linux?

**Comment by hilleer** [comment]
Hi @arunganesh-a 

It should be working for windows already. Tests are run on both windows, linux and mac. Have you been having any issues?

**Comment by rglover** [comment]
It looks like this fails on Windows if the port you're trying to stop isn't running. You get an error from the `pid-from-port` dependency saying `Failed to get pid of port <port> Error: Couldn't find a process with port <port>`.

**Comment by hilleer** [comment]
Thanks for your report @rglover. I am not entirely sure wether I would consider this as "failing" or expected behaviour :)

**Comment by rglover** [comment]
I think it's a failure in that it can break code when this occurs. Ideally it just returns `null` or `undefined` if there's no PID without throwing an error (how that's handled after the fact should be up to the dev).

**Comment by hilleer** [comment]
If you make a ping request to a url that doesn't exist, you would get a `404 Not Found` error. To me this is a somewhat similar case.

One should be able to `try-catch` such scenario without its code breaking.

I will think about it and reopen this to see if more library users will add their take or use case of it.
