### ISSUE TITLE
Support for kill -15 on Linux / Mac

### ISSUE THREAD

**Issue by lwojcik** [hilleer/kill-port-process#31]
Hi!

Just stumbled upon your library while trying to solve something on my end. Thanks for your great work!

I wonder if it would be possible to support sending `kill -15` rather than `kill -9` on Linux (maybe via an optional flag?) so that I could do `kill-port 1234 --term` or something to [kill the process gracefully](https://stackoverflow.com/questions/55796667/linux-kill-command-9-vs-15).

Additional question: are you open for a PR adding this functionality?

**Comment by hilleer** [comment]
Hi @lwojcik 

Interesting. That sounds reasonable. Yeah, please feel free to open a pull request if you like.

**Comment by hilleer** [comment]
Hi @lwojcik 

I opened this pull request that implements such a feature. I would highly appreciate if you would give it a quick look - especially consider the description in the README and if it fulfil your needs: https://github.com/hilleer/kill-port-process/pull/32

**Comment by lwojcik** [comment]
I was meaning to get this done soon-ish but you were faster than me. Sorry about that!

Well done, this is exactly what I am after.

**Comment by hilleer** [comment]
@lwojcik cool and no worries! I just came back from vacation. Will merge and make a new release in the next couple of days with this feature.

**Comment by hilleer** [comment]
Hi @lwojcik 

You can install version `3.10.0` that has this new feature.

Let me know if you happen to find any issues or have other needs/ideas 🙂 Have a nice day!
