### ISSUE TITLE
TypeError: killPortProcess is not a function

### ISSUE THREAD

**Issue by bloom510** [hilleer/kill-port-process#9]
The module isn't working as expected when attempting use, even when running any of the examples.

Tried console logging to see what's there under the hood.
`console.log(killPortProcess)`
returns `{ default: [Function: default_1] }`

**Comment by stagefright5** [comment]
@hilleer , please look into this. For now, I have downgraded to 0.0.4(As my use is only programmatic) and it is working fine.

**Comment by hilleer** [comment]
@bloom510 @stagefright5 Ok, I will look into this asap.

**Comment by hilleer** [comment]
This issue should be resolved in latest release, based on those changes: https://github.com/hilleer/kill-port-process/pull/10/files.

Please note that there is no more a default export, but you can to import it like `const { killPortProcess }  = require('kill-port-process');`
